export { default as MainLayout } from "./layout/layout.jsx"
export { default as Header } from "./header/header.jsx"
export { default as Home } from "./home/home.jsx"
export { default as Cart } from "./cart/cart.jsx"
export { default as About } from "./about/about.jsx"
export { default as Products } from "./products/products.jsx"
export { default as Errorpage } from "./errorpage/errorpage.jsx"
